const BASE = {
  1: {
    name: '1 — O Pioneiro (Autonomia e Iniciativa)',
    personality: 'Você possui um padrão de comportamento fortemente orientado para a autonomia, liderança e resolução ativa de problemas. Na psicologia, costumamos associar esse perfil a indivíduos que necessitam de um forte senso de agência (capacidade de ação) no mundo. Você não espera que a vida aconteça para você; você vai lá e faz acontecer. Esse impulso de iniciativa traz realizações incríveis, mas também pode gerar impaciência quando o ritmo dos outros não acompanha o seu. Seu maior desafio de desenvolvimento pessoal é aprender que independência não precisa significar isolamento, e que delegar ou pedir ajuda não é sinal de fraqueza.',
    relationshipVision: 'Para você, um relacionamento deve ser um espaço onde duas pessoas inteiras e fortes decidem caminhar juntas. Você rejeita a ideia de codependência. Na sua visão, o amor verdadeiro é construído sobre admiração mútua, respeito pelas individualidades e apoio para que ambos alcancem seus maiores potenciais. Você não busca alguém para te completar, mas alguém para transbordar.',
    behaviorInLove: 'No dia a dia afetivo, você demonstra amor através de atitudes práticas e de proteção. Seu estilo é direto: se há um problema, você quer resolver na hora. Você gosta de tomar a frente nas decisões do casal (onde comer, para onde viajar), o que é ótimo para parceiros indecisos, mas pode soar controlador para pessoas tão fortes quanto você. O seu principal desafio comportamental é ceder espaço para que o outro também lidere a dinâmica de vez em quando.',
    handlingConflicts: 'Em momentos de crise, sua resposta instintiva é a ação. Você prefere confrontar o problema diretamente do que empurrá-lo para debaixo do tapete. Contudo, seu tom de voz e postura podem parecer autoritários ou insensíveis sob estresse. Você precisa ter cuidado para não transformar discussões de relacionamento em "competições" onde um tem que sair vencendo.',
    destiny: 'Seu caminho de vida exige o desenvolvimento da autoconfiança sem cair na arrogância. Você foi chamado(a) para abrir portas, ser pioneiro(a) e encorajar as pessoas ao seu redor através do seu exemplo de força. A grande lição prática da sua trajetória é a empatia ativa: aprender a se colocar no lugar do outro e usar a sua força para acolher, não apenas para avançar.',
    soul: 'Emocionalmente, suas motivações mais íntimas giram em torno da liberdade de ser você mesmo(a) e da validação das suas conquistas. O que você mais busca no fundo é a sensação de ser reconhecido(a) pela sua capacidade e singularidade. Você tem um pavor inconsciente de ser controlado(a) ou de perder sua essência por causa das demandas externas.',
    expression: 'Você transmite uma postura de autossuficiência e assertividade. As pessoas frequentemente o(a) procuram para resolver problemas e pedir direcionamento. Sua comunicação corporal e verbal costuma ser direta, o que transmite confiança, mas pode intimidar pessoas mais sensíveis.',
    love: 'Você se apaixona por inteligência, força e ambição. Precisa de um parceiro que você possa admirar e que, ao mesmo tempo, respeite profundamente o seu espaço. Se você sentir que a relação está limitando seu crescimento ou exigindo dependência excessiva, a tendência é se afastar. Contudo, quando se compromete, é incrivelmente leal e protetor(a).',
    needs: 'Suas necessidades primárias na relação são: espaço, admiração e comunicação direta. A melhor forma de um parceiro amar você é encorajando seus projetos pessoais e respeitando sua necessidade de ter momentos só seus.'
  },
  2: {
    name: '2 — O Diplomata (Conexão e Empatia)',
    personality: 'Você possui um padrão comportamental de alta sensibilidade emocional e grande foco nas relações interpessoais. Em termos práticos, você é a pessoa que lê o ambiente e percebe imediatamente se alguém está desconfortável. Sua empatia é sua maior força, permitindo que você atue como pacificador(a) e crie ambientes harmoniosos. O risco dessa dinâmica é a tendência ao esquecimento de si mesmo. O seu maior desafio é aprender a dizer "não" e compreender que estabelecer limites é uma atitude saudável, não uma agressão.',
    relationshipVision: 'Para você, relacionar-se é a essência da vida. Você vê o amor como um porto seguro, uma parceria onde duas pessoas cuidam ativamente das necessidades emocionais uma da outra. A ideia de competição dentro de uma relação não faz sentido para você; o ideal é a cooperação, o acolhimento e a capacidade de ser vulnerável sem medo.',
    behaviorInLove: 'No dia a dia, você é extremamente atento(a) aos detalhes. Você demonstra amor lembrando o que o parceiro gosta, cuidando do bem-estar diário e oferecendo escuta ativa. Pode apresentar características de um estilo de apego ansioso: você precisa de reasseguramento constante de que é amado(a) e que a relação está segura. O silêncio ou a distância emocional do parceiro são os seus maiores gatilhos de ansiedade.',
    handlingConflicts: 'Você tende a evitar o confronto direto. Sua preferência é apaziguar a situação para restaurar a paz o mais rápido possível, o que muitas vezes resulta em você engolir seus próprios sentimentos. Quando os problemas se acumulam, você pode explodir ou adotar um comportamento passivo-agressivo. O aprendizado aqui é entender que conflitos bem administrados não destroem a relação, mas a fortalecem.',
    destiny: 'Sua trajetória exige o aprendizado da parceria verdadeira — aquela que não anula a individualidade. O propósito prático da sua vida é criar pontes, promover o entendimento e oferecer suporte emocional. Contudo, para fazer isso de forma sustentável, você precisa primeiro aprender a ser o seu próprio porto seguro.',
    soul: 'Seus desejos mais íntimos giram em torno da paz, da harmonia e da segurança emocional. O que você mais busca é pertencer, amar profundamente e ser correspondido(a) na mesma medida. Você tem um pavor inconsciente do abandono e da rejeição, o que muitas vezes pauta suas decisões.',
    expression: 'Você transmite uma energia receptiva, gentil e acolhedora. As pessoas tendem a desabafar com você e a se sentirem muito confortáveis na sua presença. Sua fala costuma ser cuidadosa, buscando sempre incluir os sentimentos dos outros.',
    love: 'Você se entrega de forma profunda e romântica. A lealdade e o companheirismo são fundamentais. Você não se importa em dividir os holofotes e muitas vezes prefere apoiar o sucesso do parceiro do que buscar o próprio. O desafio é não se tornar dependente emocionalmente, mantendo a sua própria vida social e interesses vivos.',
    needs: 'Suas necessidades primárias na relação são: segurança, diálogo afetivo (carinho) e presença. A melhor forma de um parceiro amar você é validando seus sentimentos, oferecendo garantias do amor que sente e sendo gentil nas palavras.'
  },
  3: {
    name: '3 — O Comunicador (Expressão e Leveza)',
    personality: 'O seu padrão de comportamento é expansivo, criativo e focado na expressão. Psicologicamente, você é movido(a) pela necessidade de interagir, de comunicar ideias e de encontrar alegria nas pequenas coisas. Você tem um olhar naturalmente otimista e uma habilidade ímpar para reverter situações pesadas usando o humor. Seu maior desafio de desenvolvimento é não usar essa mesma leveza como um mecanismo de defesa (fuga) para evitar lidar com emoções difíceis ou responsabilidades chatas, mas necessárias.',
    relationshipVision: 'Você acredita que o amor precisa ser divertido, leve e estimulante. A ideia de um relacionamento aprisionador, monótono ou cheio de regras sufocantes lhe causa repulsa. Para você, o parceiro ideal é, antes de tudo, um grande amigo e cúmplice para as aventuras da vida e para boas conversas. Vocês precisam rir das mesmas coisas.',
    behaviorInLove: 'No relacionamento, você traz entusiasmo. Gosta de planejar saídas criativas, surpreender o parceiro e manter um diálogo constante. Você demonstra afeto através da palavra (elogios, mensagens inesperadas) e do bom humor. Contudo, se a relação cair em uma rotina muito previsível, você pode rapidamente se sentir entediado(a) ou desmotivado(a).',
    handlingConflicts: 'Diante de um conflito, você tende a tentar aliviar a tensão usando o humor ou mudando de assunto. Se pressionado(a), você utilizará sua excelente habilidade com as palavras — o que pode ser perigoso, pois na raiva você sabe exatamente onde tocar na ferida do outro. É fundamental aprender a sustentar conversas desconfortáveis sem tentar escapar ou ironizar a situação.',
    destiny: 'O seu caminho envolve o domínio da comunicação e o compartilhamento da alegria. Você possui o dom natural de levantar o ânimo das pessoas e de gerar conexões. A grande lição para a sua vida é canalizar essa energia dispersa para objetivos concretos e desenvolver a disciplina emocional, unindo sua genialidade com foco.',
    soul: 'Seus anseios mais profundos envolvem a autoexpressão livre. Você quer ser ouvido(a), notado(a) e apreciado(a) por quem você é e pelas suas ideias. A motivação central da sua vida é experimentar o máximo de alegria possível. O pavor inconsciente é a sensação de ser silenciado(a) ou passar despercebido(a).',
    expression: 'Sua postura é vibrante, sociável e muitas vezes extrovertida. As pessoas são atraídas pela sua energia calorosa e pela facilidade com que você as faz sorrir. Você comunica vivacidade não apenas na fala, mas também na linguagem corporal e até no modo como se veste.',
    love: 'Você é um(a) parceiro(a) apaixonado(a) e divertido(a). O afeto floresce quando há uma conexão intelectual e comunicativa profunda. Você não sabe amar em silêncio. Se a comunicação do casal para, o seu amor parece esfriar. O aprendizado é compreender que o silêncio também pode ser um momento de intimidade.',
    needs: 'Suas necessidades primárias na relação são: diálogo constante, estímulo (novidades) e validação (ser apreciado/a). A melhor forma de um parceiro amar você é prestando atenção no que você diz, embarcando nas suas ideias criativas e cultivando o bom humor.'
  },
  4: {
    name: '4 — O Construtor (Estrutura e Consistência)',
    personality: 'Você opera através de um padrão de comportamento pautado na praticidade, organização e no senso de dever. Sob o ponto de vista da psicologia comportamental, você precisa de previsibilidade e estrutura para se sentir seguro(a). Você é a pessoa que planeja, executa e sustenta as responsabilidades, sendo um pilar para a família e amigos. O seu maior desafio é a rigidez: a tendência a acreditar que existe apenas "um jeito certo" de fazer as coisas e a dificuldade em lidar com imprevistos.',
    relationshipVision: 'Para você, amor não é apenas um sentimento; é uma escolha diária demonstrada através de atitudes concretas e compromisso. Você não perde tempo com amores de verão ou joguinhos desnecessários. Uma relação, na sua visão, é uma parceria de vida projetada para o longo prazo, focada em construir uma família, um patrimônio e uma base sólida.',
    behaviorInLove: 'No dia a dia, você é extremamente presente, confiável e focado(a) na resolução prática dos problemas domésticos. Sua forma primária de demonstrar amor é pelo serviço (cuidar da casa, resolver questões financeiras, garantir que tudo funcione). Você pode ter dificuldade com demonstrações verbais excessivas de afeto, preferindo provar o que sente com consistência.',
    handlingConflicts: 'Em uma briga, você é pragmático(a) e altamente racional. Tende a apresentar os fatos e buscar a lógica da situação, o que pode fazer com que parceiros mais emocionais sintam que você é frio(a) ou calculista. Você lida mal com explosões emocionais irracionais. Seu desafio é aprender a validar os sentimentos do outro antes de tentar oferecer uma solução lógica.',
    destiny: 'Sua trajetória exige disciplina e a construção de alicerces. Você é chamado(a) a colocar ordem no caos e a manifestar planos materiais. Contudo, o grande aprendizado da sua vida é entender que a flexibilidade não quebra a estrutura; ela a torna adaptável. Aprender a relaxar é vital para a sua saúde mental.',
    soul: 'Emocionalmente, suas motivações giram em torno da estabilidade, da ordem e da sensação de dever cumprido. Você busca desesperadamente a segurança e o controle sobre o seu ambiente. O seu maior medo inconsciente é a instabilidade, a ruína financeira ou a traição da confiança.',
    expression: 'Você transmite uma aura de seriedade, responsabilidade e estabilidade. As pessoas instintivamente confiam as chaves e os segredos a você, sabendo que você fará o que é certo. Sua comunicação é clara, pontual e focada no mundo real.',
    love: 'Você é um(a) parceiro(a) extremamente leal. Quando decide se comprometer, é para valer. Contudo, a rotina de muito trabalho e o excesso de responsabilidades podem sufocar o romantismo. Para o amor prosperar, é importante agendar conscientemente momentos de lazer e nutrir a paixão.',
    needs: 'Suas necessidades primárias na relação são: lealdade, respeito pela rotina e previsibilidade. A melhor forma de um parceiro amar você é cumprindo com a palavra, compartilhando o peso das responsabilidades diárias e demonstrando confiança nas suas atitudes.'
  },
  5: {
    name: '5 — O Explorador (Liberdade e Adaptabilidade)',
    personality: 'O seu comportamento é marcado por um desejo intenso de movimento, novidade e experimentação. Psicologicamente, a rotina funciona como um supressor da sua energia vital. Você possui uma capacidade de adaptação impressionante e uma mente rápida, que consegue processar muitas informações simultaneamente. Seu grande desafio pessoal é lidar com o risco da dispersão e entender que a liberdade absoluta pode, paradoxalmente, se transformar numa prisão quando impede você de criar raízes profundas.',
    relationshipVision: 'Você vê o relacionamento como uma grande jornada a ser compartilhada. Você rejeita as noções tradicionais de posse, controle e ciúme. Para você, uma relação saudável é aquela que expande os horizontes de ambos em vez de limitar. O parceiro ideal não é alguém que fica te esperando em casa, mas alguém que viaja e descobre o mundo ao seu lado.',
    behaviorInLove: 'Na dinâmica de casal, você traz intensidade, paixão e surpresas. Você é mestre em quebrar a rotina com um convite inesperado ou uma nova ideia. Seu afeto é vivaz e sedutor. Porém, sua necessidade de espaço pode ser interpretada como desinteresse ou instabilidade por parceiros mais convencionais. Você precisa de respiros (sair sozinho, ter seus próprios hobbies) para se manter apaixonado(a) na relação.',
    handlingConflicts: 'Diante de cobranças excessivas ou tentativas de controle, a sua reação imediata é a fuga (física ou emocional). Em discussões, você tem argumentos rápidos, mas sua tolerância para "discutir a relação" durante horas é muito baixa. Para resolver conflitos com você, o melhor é o diálogo objetivo, feito com respeito à sua independência.',
    destiny: 'Seu caminho de vida envolve a busca pelas experiências, quebra de paradigmas e o aprendizado sobre o uso construtivo da liberdade. Você ensina aos outros a não terem medo da mudança. A grande lição que a vida lhe reserva é entender que o compromisso verdadeiro não anula a sua liberdade, mas fornece uma base segura para você voar.',
    soul: 'Emocionalmente, suas motivações giram em torno da curiosidade, da aventura e da aversão ao tédio. O que move o seu interior é a sensação de que a vida é um leque infinito de opções. O medo inconsciente que pauta suas ações é o de ficar preso(a), paralisado(a) ou perder oportunidades de viver.',
    expression: 'Você transmite uma energia magnética, mutável e um pouco misteriosa. As pessoas acham você fascinante e dinâmico(a). Sua fala é rápida e você facilmente pula de um assunto para o outro, mantendo todos sempre interessados e um pouco na expectativa do que virá a seguir.',
    love: 'Você é um(a) amante inesquecível e intenso(a), porém exige que a chama seja alimentada constantemente com novidades. Relações longas dão muito certo quando há projetos novos acontecendo continuamente (viagens, novos aprendizados, mudança de casa). Se a relação estagnar, você perde a motivação.',
    needs: 'Suas necessidades primárias na relação são: espaço pessoal absoluto, ausência de rotina estrita e estímulos novos. A melhor forma de um parceiro amar você é confiando no seu caráter, não cobrando explicações de cada passo seu e sendo aberto(a) a experimentar a vida ao seu lado.'
  },
  6: {
    name: '6 — O Cuidador (Acolhimento e Responsabilidade Afetiva)',
    personality: 'Seu padrão comportamental é fortemente centrado na família, na harmonia doméstica e na responsabilidade afetiva pelas pessoas. Na psicologia, você muitas vezes se coloca no papel do "salvador" ou cuidador principal. Você tira enorme satisfação de nutrir as pessoas e resolver os problemas alheios. Contudo, essa característica pode gerar uma sobrecarga massiva e um sentimento de ser explorado(a) quando a balança do dar-e-receber não está equilibrada. Seu principal desafio é aprender que o autocuidado não é egoísmo.',
    relationshipVision: 'O amor é o centro do seu mundo. Você vê um relacionamento como a criação de um lar físico e emocional, um espaço protegido onde a família e os afetos possam florescer com segurança. Para você, amar é cuidar, e não existe parceria sem entrega total e empatia pelas vulnerabilidades um do outro.',
    behaviorInLove: 'No dia a dia, você é afetuoso(a), atento(a) e muito voltado(a) para o conforto da família. Você gosta de mimar o parceiro, seja fazendo uma comida especial, seja garantindo que a casa esteja perfeita. Tende a assumir muito mais responsabilidades do que deveria, justificando com um "deixa que eu faço". O risco disso é criar parceiros acomodados ou dependentes, o que, a longo prazo, gera ressentimento em você.',
    handlingConflicts: 'Em conflitos, sua maior preocupação é restaurar a paz, muitas vezes aceitando a culpa por coisas que não fez apenas para parar a briga. Quando magoados, os indivíduos deste perfil tendem ao modo "mártir", fechando-se e esperando que o parceiro perceba o quanto vocês se sacrificaram. O aprendizado vital é aprender a comunicar suas insatisfações abertamente antes que virem grandes frustrações.',
    destiny: 'Sua trajetória está ligada à construção de laços familiares comunitários e à cura através do amor prático. A grande lição que o seu caminho demanda é o estabelecimento de limites saudáveis. Você precisa entender que não pode salvar ninguém que não queira ser salvo, e que a sua paz interior também importa.',
    soul: 'As motivações mais profundas da sua alma giram em torno da necessidade de ser útil, de amar e de ser amado(a) em troca com lealdade profunda. O que mais o(a) impulsiona é ver as pessoas que ama felizes e em segurança. Seu pavor inconsciente é a sensação de ser rejeitado(a) ou de falhar na proteção da sua família.',
    expression: 'Você transmite uma postura de acolhimento incondicional, bondade e responsabilidade. As pessoas veem em você uma figura parental, aquele(a) amigo(a) para quem se liga quando tudo dá errado. Sua linguagem corporal é protetora e sua voz tende a ser reconfortante.',
    love: 'Você é profundo(a) e leal. Em um relacionamento, busca antes de tudo a estabilidade afetiva para, a partir daí, construir projetos em conjunto. Exige muita atenção emocional e fica profundamente ferido(a) com a frieza. Quando percebe que a relação é recíproca, você se torna o pilar mais forte da união.',
    needs: 'Suas necessidades primárias na relação são: demonstrações claras de afeto, valorização pelo seu esforço diário e harmonia em casa. A melhor forma de um parceiro amar você é assumindo responsabilidades ativamente para que você possa descansar, e reconhecendo verbalmente tudo o que você faz pela relação.'
  },
  7: {
    name: '7 — O Sábio (Profundidade e Introspecção)',
    personality: 'O seu funcionamento mental é voltado para a análise, o pensamento crítico e a busca profunda pelo sentido da vida. Sob um prisma psicológico, você tende à introversão, precisando de bastante tempo a sós para recarregar suas energias (bateria social). Você não tem paciência para conversas superficiais ou relações fúteis. O seu grande desafio de desenvolvimento é evitar o isolamento completo e o excesso de ceticismo, aprendendo a abrir seu coração mesmo quando a lógica não explica tudo.',
    relationshipVision: 'Você encara o amor de forma profunda, até espiritual, mas com uma abordagem altamente seletiva. Para você, uma relação precisa ser um encontro de mentes e almas. Você prefere ficar sozinho(a) a estar com alguém que não lhe ofereça estímulo intelectual e compreensão do seu mundo interior. Relacionamento é sinônimo de cumplicidade silenciosa e respeito ao mistério humano.',
    behaviorInLove: 'No dia a dia, você é reservado(a), mas profundamente leal e observador(a). O afeto nem sempre é demonstrado através de toques ou excesso de palavras, mas prestando atenção nas entrelinhas do comportamento do outro e provendo suporte nos momentos críticos. Seu estilo afetivo requer a manutenção do espaço individual. Quando o parceiro compreende que o seu silêncio não é desamor, a relação se torna inabalável.',
    handlingConflicts: 'Em uma crise, sua reação é o recuo estratégico. Você precisa processar mentalmente o problema antes de falar, o que pode deixar parceiros ansiosos em estado de desespero por respostas. Você costuma usar argumentos lógicos, frios e irrefutáveis, dissecando o problema. O desafio é lembrar que relações humanas não são equações matemáticas; as emoções precisam ser validadas mesmo que pareçam irracionais.',
    destiny: 'Seu caminho envolve o aprofundamento filosófico, espiritual ou analítico da realidade. Você foi chamado(a) para encontrar as respostas escondidas e para atuar como um conselheiro ou referência de conhecimento. O aprendizado da sua vida é equilibrar a razão absoluta com a capacidade de sentir e de ter fé nas coisas que não se podem ver.',
    soul: 'Sua alma deseja privacidade, sabedoria e a busca pela verdade de todas as coisas. A maior motivação é entender o porquê da existência. O seu medo inconsciente é o da invasão de privacidade, o pavor de parecer ignorante ou de se expor emocionalmente e ser julgado(a) por sua vulnerabilidade.',
    expression: 'Você transmite uma aura de mistério, intelectualidade e certa distância protetora. As pessoas frequentemente o(a) acham fascinante, porém difícil de acessar emocionalmente. Sua comunicação é precisa e você detesta o desperdício de palavras.',
    love: 'Você demora a confiar e se apaixonar plenamente. O seu intelecto costuma colocar barreiras de teste antes de permitir que o coração se abra. Contudo, quando encontra alguém capaz de nadar nas suas águas profundas, o seu amor é maduro, consciente e de uma lealdade rara no mundo atual.',
    needs: 'Suas necessidades primárias na relação são: silêncio, espaço pessoal e intimidade intelectual. A melhor forma de um parceiro amar você é oferecendo conversas inteligentes, respeitando sua necessidade de recolhimento sem cobrar afeto exagerado e sendo autêntico e verdadeiro.'
  },
  8: {
    name: '8 — O Realizador (Estratégia e Execução)',
    personality: 'Seu padrão comportamental é focado na eficiência, na busca pela excelência e no gerenciamento de poder ou recursos materiais. Psicologicamente, você é conduzido(a) por um foco extremo em metas e por uma resiliência gigantesca sob pressão. Você entende como o mundo real funciona e sabe se posicionar estrategicamente para alcançar o topo. O seu maior desafio é lidar com o risco do autoritarismo, a tendência ao workaholism e a dificuldade em aceitar a própria vulnerabilidade.',
    relationshipVision: 'Você vê o relacionamento como uma aliança de poder e construção conjunta. Para você, o parceiro ideal é como um co-piloto nos negócios da vida. O romantismo por si só não sustenta uma relação; você busca alguém que agregue valor (não apenas financeiro, mas de status, inteligência e força), com quem você possa dividir a conquista do mundo.',
    behaviorInLove: 'No ambiente afetivo, você é incrivelmente provedor(a) e protetor(a). Você gosta de oferecer o melhor da vida (boas experiências, segurança financeira, status) como forma de demonstrar seu amor. Em casa, no entanto, pode ter dificuldade em "desligar" a mentalidade de CEO, acabando por tratar a gestão familiar como um projeto corporativo. O grande desafio é aprender a relaxar na intimidade e não avaliar o parceiro apenas pelos seus resultados ou produtividade.',
    handlingConflicts: 'Diante de atritos, você é direto(a), intimidador(a) e orientado(a) para soluções drásticas. Se o parceiro tentar "jogar", você rapidamente tomará o controle da situação. Sob estresse, pode adotar uma postura de frieza emocional punitiva. É crucial desenvolver a paciência tática, lembrando que o parceiro não é um funcionário e que discussões amorosas não se tratam de ganhar ou perder autoridade.',
    destiny: 'Sua vida está voltada para o domínio da matéria, da liderança e da abundância financeira. Você tem o dom de gerar riqueza e oportunidades. A grande lição que o destino exige de você é o uso ético e espiritual do poder, e a compreensão de que os verdadeiros tesouros não se compram.',
    soul: 'Suas necessidades emocionais são pautadas por reconhecimento, respeito absoluto e controle sobre o próprio destino. O que mais o(a) move é o desejo de não depender de ninguém. O medo mais profundo e paralisante que carrega é o do fracasso público, da humilhação ou da submissão.',
    expression: 'Você exala autoridade natural, sofisticação e confiança. Ao entrar em um ambiente, sua presença é notada sem que precise fazer esforço. Sua comunicação verbal é objetiva e sua postura exige respeito instantâneo, afastando pessoas inseguras.',
    love: 'Você é um(a) parceiro(a) exigente, que não se contenta com pouco. Precisa de alguém à sua altura, que tenha a própria carreira e brilho, mas que compreenda a sua agenda intensa. Quando a confiança se estabelece, você é capaz de mover montanhas para proteger e elevar a pessoa que escolheu amar.',
    needs: 'Suas necessidades primárias na relação são: ambição compartilhada, lealdade absoluta e competência. A melhor forma de um parceiro amar você é demonstrando que sabe se virar, valorizando suas conquistas com admiração genuína e sendo seu porto seguro de descanso emocional.'
  },
  9: {
    name: '9 — O Humanitário (Empatia Universal e Desapego)',
    personality: 'Você opera a partir de um padrão de comportamento focado na compreensão ampla, na filantropia e na busca por grandes ideais sociais ou humanitários. Sob o ponto de vista da psicologia, você apresenta uma inteligência emocional global, sendo capaz de amar e aceitar pessoas das mais diversas origens. Você tem uma "alma velha", compreendendo rapidamente as motivações alheias. O seu grande desafio de desenvolvimento é não se perder em um idealismo irreal, e evitar a síndrome de mártir, que ocorre quando você tenta salvar o mundo à custa da sua saúde mental e financeira.',
    relationshipVision: 'Você vê o amor de forma transcendente, acreditando que a união entre duas pessoas deve servir a um propósito maior (ex: ajudar a comunidade, criar arte, promover cura). A relação ideal precisa ter um significado profundo e valores muito alinhados. O egoísmo puro ou futilidade em um parceiro afasta você imediatamente.',
    behaviorInLove: 'No dia a dia do relacionamento, você é generoso(a), compassivo(a) e extremamente tolerante. Você consegue ver o melhor no parceiro, mesmo quando ele erra. Esse dom do perdão e da aceitação incondicional é lindo, mas pode levá-lo(a) a permanecer em relações tóxicas por acreditar que "com amor ele(a) vai mudar". O seu desafio diário é focar a sua compaixão no aqui e agora, sem idealizar quem a pessoa ainda não é.',
    handlingConflicts: 'Em brigas, sua abordagem costuma ser a da compreensão do erro do outro. Você rapidamente busca entender o "porquê" a pessoa agiu mal, muitas vezes relevando o seu próprio ressentimento. O lado negativo é o acúmulo silencioso de decepções. Quando o limite finalmente é ultrapassado, você pode adotar o "corte final", desaparecendo da vida do parceiro de forma definitiva, pois o ciclo para você se encerrou.',
    destiny: 'Sua trajetória é de conclusões, de ensinar através do desapego e do amor incondicional. Você foi chamado(a) para influenciar muitas pessoas, atuando como professor(a) moral, filantropo(a) ou guia. O aprendizado da vida é não se prender ao passado e aceitar a transitoriedade das coisas.',
    soul: 'As motivações mais profundas da sua alma dizem respeito à transcendência do sofrimento humano, à justiça e ao propósito universal. Você quer sentir que a sua vida tem um impacto positivo real. O medo inconsciente que carrega é o de ser sugado(a) pelas trivialidades mesquinhas ou de perceber que o mundo é cruel sem remédio.',
    expression: 'Você transmite uma aura de sabedoria serena, aceitação e magnetismo compassivo. As pessoas confiam em você instintivamente, percebendo a sua ausência de julgamento. Sua comunicação é inspiradora, muitas vezes tocando o emocional de quem escuta.',
    love: 'Você é um(a) amante generoso(a) e espiritual. Quando se entrega, ama a essência da pessoa, e não apenas o que ela possui ou aparenta. Contudo, essa abrangência do seu amor pode fazer com que parceiros mais possessivos sintam que não são "exclusivos" ou especiais o suficiente, já que você se dedica tanto ao mundo quanto a eles.',
    needs: 'Suas necessidades primárias na relação são: propósitos maiores compartilhados, profundidade emocional e desapego material em favor de valores morais. A melhor forma de um parceiro amar você é compartilhando da sua compaixão pelas outras pessoas e entendendo a sua necessidade de espaço para atuar no mundo.'
  }
};

// Números Mestres utilizam a base ajustada, com foco em potenciais extremados
BASE[11] = { 
  ...BASE[2], 
  name: '11 — O Mestre Intuitivo (Inspiração e Sensibilidade Elevada)', 
  personality: 'Como portador do número mestre 11, você vive a sensibilidade do número 2 em uma oitava muito mais alta. A sua intuição é quase palpável; psicologicamente, você processa o ambiente, os sentimentos e os micro-comportamentos das pessoas com uma velocidade impressionante. Você carrega um desejo intenso de inspirar os outros. O seu desafio monumental é o controle da ansiedade nervosa provocada por absorver energia demais do ambiente. Aprender a aterrar essa energia elétrica (grounding) é vital.',
  relationshipVision: 'Para você, o amor é uma jornada de despertar espiritual mútuo. Você não quer apenas um(a) parceiro(a); quer uma conexão que transcenda o ordinário. Você busca um encontro de almas que permita o crescimento intelectual, espiritual e emocional de ambos.',
  behaviorInLove: 'A sua dedicação ao parceiro é intensa e telepática. Muitas vezes você sabe o que o parceiro sente antes mesmo que ele fale. Contudo, essa hipersensibilidade pode torná-lo(a) muito reativo(a) a mudanças bruscas de humor do outro. Você tende a esperar reciprocidade imediata na mesma profundidade, frustrando-se com parceiros que têm dificuldades em verbalizar as emoções.',
  handlingConflicts: 'As discussões têm um forte impacto no seu sistema nervoso. Você evita atritos não por fraqueza, mas pelo desgaste que causam. Porém, quando pressionado(a), sua intuição permite que você use as palavras como bisturis emocionais. O ideal é aprender ferramentas práticas de comunicação não violenta para não ser refém das ondas de intensidade.',
  destiny: 'Seu propósito central é inspirar e elevar consciências — não liderando pela força, mas pelo exemplo, pela arte, intuição ou psicologia. A grande lição de vida é não se deixar esmagar pelos próprios dons, desenvolvendo confiança em sua voz interior.',
  soul: 'Sua alma anseia por conexões transcendentais, pela beleza suprema e por insights profundos. O maior pavor inconsciente é a desconexão com a sua intuição, bem como o medo de não ser compreendido(a) pela maioria.',
  expression: 'Você emite uma energia magnética, um tanto elétrica e inspiradora. As pessoas se sentem fascinadas por você, notando um brilho singular na sua forma de falar e na empatia profunda que você transmite.',
  love: 'A paixão do 11 é vulcânica, poética e inesquecível. Se você mantiver os pés no chão, o seu relacionamento será de uma riqueza emocional rara e indestrutível.',
  needs: 'Você precisa de validação emocional, de tempo para recarga energética e de um parceiro que confie cegamente na sua intuição, oferecendo-lhe a paz de um refúgio seguro.'
};

BASE[22] = { 
  ...BASE[4], 
  name: '22 — O Mestre Construtor (Visão Sistêmica e Realização Massiva)', 
  personality: 'O mestre 22 une a capacidade visionária ao pragmatismo extremo. Psicologicamente, você possui uma visão sistêmica invejável; consegue imaginar o produto final e traçar milimetricamente cada passo material para alcançá-lo. Você não veio para pequenos projetos. O desafio desse perfil é o peso excessivo das próprias expectativas e o risco de megalomania ou paralisia pelo perfeccionismo.',
  relationshipVision: 'Seu relacionamento ideal é uma potência colaborativa. Você entende o amor como a construção conjunta de um legado, de grandes projetos de vida. O parceiro é a pessoa em quem você precisa confiar mais do que em si mesmo(a). Sem respeito prático, não há amor sustentável na sua visão.',
  behaviorInLove: 'No relacionamento afetivo, você organiza as bases da vida de forma impecável. Proporciona o mais alto nível de suporte e estrutura. Porém, pelo foco excessivo nos resultados e planos futuros, pode pecar no momento presente, esquecendo-se da fragilidade e leveza necessárias no dia a dia afetivo.',
  handlingConflicts: 'Você trata os conflitos relacionais quase como crises gerenciais. Sua postura é imponente e focada na reestruturação do acordo. Você destesta discussões focadas no "mimimi" sem propostas práticas de solução. É necessário o desenvolvimento de uma escuta afetiva que acolha o problema sem tentar consertá-lo no mesmo segundo.',
  destiny: 'Sua trajetória é para edificar algo que ficará para as próximas gerações, seja uma empresa, uma inovação, um método ou uma família formidável. A lição primordial é aprender a delegar e entender que o fracasso faz parte do processo construtivo.',
  soul: 'Sua alma almeja o impacto, a concretização de grandes ideais no mundo físico. A sua motivação é transformar sonhos utópicos em realidade palpável. O medo mais aterrorizante é viver todo o seu potencial apenas na imaginação e não construir nada real.',
  expression: 'Sua postura projeta autoridade inquestionável, calma sob pressão e competência extrema. As pessoas o(a) veem como um comandante natural.',
  love: 'Quando um(a) mestre 22 ama, a vida do parceiro é inteiramente elevada. Você cria condições para que o parceiro cresça exponencialmente ao seu lado.',
  needs: 'Você necessita de previsibilidade operacional, confiança irrestrita e um parceiro capaz de aguentar a pressão dos seus grandes projetos, mantendo a ternura viva em casa.'
};

const MEANINGS = {};
for (const key of Object.keys(BASE)) {
  MEANINGS[key] = {
    name: BASE[key].name,
    personality: BASE[key].personality,
    relationshipVision: BASE[key].relationshipVision,
    behaviorInLove: BASE[key].behaviorInLove,
    handlingConflicts: BASE[key].handlingConflicts,
    destiny: BASE[key].destiny,
    soul: BASE[key].soul,
    expression: BASE[key].expression,
    love: BASE[key].love,
    needs: BASE[key].needs
  };
}

export default MEANINGS;
